# Generated by Django 4.2.5 on 2023-10-04 08:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('line', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zuizhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('belong_to_user3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_user3', to='mainapp.date_user')),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('=', '='), ('<', '<'), ('>', '>')], max_length=2)),
                ('constraint_value', models.FloatField()),
                ('belong_to_user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_user1', to='mainapp.date_user')),
            ],
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('belong_to_equation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='mainapp.equation')),
                ('belong_to_user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_user2', to='mainapp.date_user')),
            ],
        ),
    ]
